### ISSUE TITLE
WindowCovering doesn't work

### ISSUE THREAD

**Issue by jrburk** [hap-java/HAP-Java#40] opened 2018-01-06 20:31 UTC
When I use WindowCovering I get an error from the iOS Home app "Home couldn't connect to this accessory.". I don't see any error in the debug console.

**Comment by timcharper** [comment] 2019-02-04 08:07
Duplicate of #56

**Comment by timcharper** [comment] 2019-02-18 07:50
@beowulfe let's close this as a duplicate of #56; I can definitely reproduce this bug and it is caused by the inclusion of `HoldPositionCharacteristic`

**Comment by sobeos** [comment] 2020-01-04 23:43
No update since 10 month. Why is the issue not closed?

**Closed** 2020-01-07 01:47 UTC
